castware-operator:
  fullnameOverride: castware-operator

  # GLOBAL FIX: This tells all components (Agent/Spot Handler) 
  # to look for the cluster named "castai-gke-connect"
  clusterName: "castai-gke-connect"

  crds:
    install: false
    keep: false

  apiKeySecret:
    enabled: true
    apiKey: "b985e8260ece5d9e851036889d1bb85b925623e295496ebe6b9c33e1b1ff72d8"
    name: "castai-api-key"

  defaultCluster:
    enabled: true
    terraform: false
    provider: "gke"
    name: "castai-gke-connect" 
    api:
      apiUrl: "https://api.cast.ai"
  
  defaultComponents:
    enabled: true

  namespace: castai-agent
