castware-operator:
  fullnameOverride: castware-operator
  clusterName: "castai"

  crds:
    install: false
    keep: false

  apiKeySecret:
    enabled: true
    # USE THE NEW TOKEN FROM YOUR SCRIPT OUTPUT
    apiKey: "08c19b5f1fae10e41dbde6612f9ee8b9969c3cc3335f1b8437d3ce56246a164b"
    name: "castai-api-key"

  defaultCluster:
    enabled: true
    terraform: false
    provider: "gke"
    name: "castai"
    api:
      apiUrl: "https://api.cast.ai"
  
  # These match the "true" flags in your script
  defaultComponents:
    enabled: true
    autoscaler: true        # INSTALL_AUTOSCALER=true
    podPinner: true         # INSTALL_POD_PINNER=true

  namespace: castai-agent
