castware-operator:
  apiKeySecret:
    enabled: false
    name: "castai-api-key"

  defaultCluster:
    terraform: false
    provider: "gke"
    # OPTIONAL: Replace with your actual GKE cluster name
    name: "castai-gke-connect"
    api:
      apiUrl: "https://api.cast.ai"
  
  defaultComponents:
    enabled: true

  # Ensures everything lands in the right place
  namespace: castai-agent
