castware-operator:
  apiKeySecret:
    enabled: true  # <--- Set this to true
    apiKey: "b985e8260ece5d9e851036889d1bb85b925623e295496ebe6b9c33e1b1ff72d8" # <--- Use the real key
    name: "castai-api-key"

  defaultCluster:
    terraform: false
    provider: "gke"
    name: "castai-gke-connect"
    api:
      apiUrl: "https://api.cast.ai"
  
  defaultComponents:
    enabled: true

  namespace: castai-agent
