castware-operator:
  # FIX: This ensures the webhook service name matches what the operator expects
  fullnameOverride: castware-operator

  crds:
    install: false
    keep: false

  apiKeySecret:
    enabled: true
    apiKey: "b985e8260ece5d9e851036889d1bb85b925623e295496ebe6b9c33e1b1ff72d8"
    name: "castai-api-key"

  defaultCluster:
    terraform: false
    provider: "gke"
    name: "castai-gke-connect"
    api:
      apiUrl: "https://api.cast.ai"
  
  defaultComponents:
    enabled: true

  namespace: castai-agent
